"""Verification repository: all database access for the verifications table.

Phase 2C addition: transition_status for atomic conditional state transitions.
"""

import json
import logging
import uuid
from decimal import Decimal
from typing import Any, Dict, List, Optional, Union

from app.core.database import DatabaseManager, database_manager

logger = logging.getLogger("verifai.repositories.verification")


class VerificationRepository:
    """Repository providing CRUD access to the ``verifications`` table.

    All methods follow the same pattern as ``UserRepository``:
    - Accept plain Python types
    - Acquire a connection from the pool for each operation
    - Return plain ``Dict[str, Any]`` rows (never ORM objects)
    - Raise ``RuntimeError`` when the pool is not available

    This keeps every caller free of asyncpg-specific knowledge and makes
    unit testing straightforward with mock pools.
    """

    def __init__(self, db_manager: DatabaseManager = database_manager) -> None:
        self.db = db_manager

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_pool(self):
        """Return the active pool or raise if the database is not connected."""
        pool = self.db.get_pool()
        if pool is None:
            raise RuntimeError("Database connection is not available")
        return pool

    def _row_to_dict(self, record) -> Dict[str, Any]:
        """Convert an asyncpg Record (or dict mock) to a plain dict.

        ``evidence`` is stored as JSONB and comes back as a JSON string from
        asyncpg; we normalise it to a Python list/dict here so callers never
        see raw JSON strings.
        """
        row = dict(record)
        if row.get("evidence") is not None and isinstance(row["evidence"], str):
            try:
                row["evidence"] = json.loads(row["evidence"])
            except (ValueError, TypeError):
                row["evidence"] = None
        return row

    # ------------------------------------------------------------------
    # Write operations
    # ------------------------------------------------------------------

    async def create_verification(
        self,
        user_id: Union[str, uuid.UUID],
        claim: str,
    ) -> Dict[str, Any]:
        """Insert a new verification in ``pending`` state.

        The ID is generated by the database (``gen_random_uuid()``).
        Returns the full persisted row.
        """
        uid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        query = """
            INSERT INTO verifications (user_id, claim)
            VALUES ($1, $2)
            RETURNING
                id, user_id, claim, status, verdict,
                trust_score, evidence, error_message,
                created_at, updated_at;
        """
        pool = self._get_pool()
        async with pool.acquire() as conn:
            record = await conn.fetchrow(query, uid, claim)
            if record is None:
                raise RuntimeError("Failed to insert verification record")
            return self._row_to_dict(record)

    async def update_verification(
        self,
        verification_id: Union[str, uuid.UUID],
        status: str,
        verdict: Optional[str] = None,
        trust_score: Optional[Decimal] = None,
        evidence: Optional[Any] = None,
        error_message: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Update the result fields of an existing verification.

        Intended for use by the verification engine (Phase 2B+) once
        processing completes. Returns the updated row or ``None`` if the ID
        does not exist.
        """
        vid = (
            uuid.UUID(str(verification_id))
            if not isinstance(verification_id, uuid.UUID)
            else verification_id
        )
        # Serialise evidence list/dict → JSON string for JSONB storage
        evidence_json: Optional[str] = None
        if evidence is not None:
            evidence_json = json.dumps(evidence)

        query = """
            UPDATE verifications
            SET
                status        = $2::verification_status,
                verdict       = $3,
                trust_score   = $4,
                evidence      = $5::jsonb,
                error_message = $6,
                updated_at    = NOW()
            WHERE id = $1
            RETURNING
                id, user_id, claim, status, verdict,
                trust_score, evidence, error_message,
                created_at, updated_at;
        """
        pool = self._get_pool()
        async with pool.acquire() as conn:
            record = await conn.fetchrow(
                query, vid, status, verdict, trust_score, evidence_json, error_message
            )
            return self._row_to_dict(record) if record else None

    async def transition_status(
        self,
        verification_id: Union[str, uuid.UUID],
        expected_status: str,
        new_status: str,
        error_message: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """Atomically transition a verification from ``expected_status`` to ``new_status``.

        The ``WHERE status = $expected_status`` predicate prevents:

        - Invalid transitions (e.g. completed → processing)
        - Race conditions between concurrent processing attempts

        Returns:
            The updated record dict if the transition succeeded.
            ``None`` if the row was not found **or** the current status
            did not match ``expected_status`` — callers must treat both
            cases the same way to avoid leaking state information.

        Raises:
            RuntimeError: When the database pool is unavailable.
        """
        vid = (
            uuid.UUID(str(verification_id))
            if not isinstance(verification_id, uuid.UUID)
            else verification_id
        )
        query = """
            UPDATE verifications
            SET
                status        = $3::verification_status,
                error_message = $4,
                updated_at    = NOW()
            WHERE id = $1
              AND status = $2::verification_status
            RETURNING
                id, user_id, claim, status, verdict,
                trust_score, evidence, error_message,
                created_at, updated_at;
        """
        pool = self._get_pool()
        async with pool.acquire() as conn:
            record = await conn.fetchrow(
                query, vid, expected_status, new_status, error_message
            )
            return self._row_to_dict(record) if record else None

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    async def get_verification_by_id(
        self,
        verification_id: Union[str, uuid.UUID],
    ) -> Optional[Dict[str, Any]]:
        """Fetch a single verification row by its UUID primary key."""
        vid = (
            uuid.UUID(str(verification_id))
            if not isinstance(verification_id, uuid.UUID)
            else verification_id
        )
        query = """
            SELECT
                id, user_id, claim, status, verdict,
                trust_score, evidence, error_message,
                created_at, updated_at
            FROM verifications
            WHERE id = $1;
        """
        pool = self._get_pool()
        async with pool.acquire() as conn:
            record = await conn.fetchrow(query, vid)
            return self._row_to_dict(record) if record else None

    async def get_verifications_by_user(
        self,
        user_id: Union[str, uuid.UUID],
        limit: int = 20,
        offset: int = 0,
    ) -> List[Dict[str, Any]]:
        """Return a paginated list of verifications for the given user.

        Results are ordered by most-recent first (``created_at DESC``).
        """
        uid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        query = """
            SELECT
                id, user_id, claim, status, verdict,
                trust_score, evidence, error_message,
                created_at, updated_at
            FROM verifications
            WHERE user_id = $1
            ORDER BY created_at DESC
            LIMIT $2 OFFSET $3;
        """
        pool = self._get_pool()
        async with pool.acquire() as conn:
            records = await conn.fetch(query, uid, limit, offset)
            return [self._row_to_dict(r) for r in records]

    async def count_verifications_by_user(
        self,
        user_id: Union[str, uuid.UUID],
    ) -> int:
        """Return the total number of verifications for a user (used for pagination)."""
        uid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        query = "SELECT COUNT(*) FROM verifications WHERE user_id = $1;"
        pool = self._get_pool()
        async with pool.acquire() as conn:
            count = await conn.fetchval(query, uid)
            return int(count) if count is not None else 0

    async def delete_verification(
        self,
        verification_id: Union[str, uuid.UUID],
        user_id: Union[str, uuid.UUID],
    ) -> bool:
        """Delete a verification, scoped to its owner for safety.

        Returns ``True`` if the row was deleted, ``False`` if it was not
        found (or belongs to a different user).
        """
        vid = (
            uuid.UUID(str(verification_id))
            if not isinstance(verification_id, uuid.UUID)
            else verification_id
        )
        uid = uuid.UUID(str(user_id)) if not isinstance(user_id, uuid.UUID) else user_id
        query = "DELETE FROM verifications WHERE id = $1 AND user_id = $2;"
        pool = self._get_pool()
        async with pool.acquire() as conn:
            result = await conn.execute(query, vid, uid)
            # asyncpg returns "DELETE <count>"
            return result == "DELETE 1"


# Default singleton instance
verification_repository = VerificationRepository()
