'use client';

import React, { useState } from 'react';
import {
  ShieldCheck,
  Search,
  CheckCircle,
  AlertTriangle,
  XCircle,
  HelpCircle,
  ExternalLink,
  Copy,
  Download,
  Check,
  Sparkles,
  Layers,
  FileText,
  Filter,
} from 'lucide-react';

interface ClaimItem {
  id: string;
  text: string;
  verdict: 'SUPPORTED' | 'PARTIALLY_SUPPORTED' | 'REFUTED' | 'UNVERIFIED';
  confidence: number;
  sources: {
    title: string;
    url: string;
    snippet: string;
    relevance: number;
  }[];
}

export default function VerificationPage() {
  const [inputText, setInputText] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [hasResult, setHasResult] = useState(false);
  const [copied, setCopied] = useState(false);
  const [filterVerdict, setFilterVerdict] = useState<string>('ALL');
  const [expandedClaimId, setExpandedClaimId] = useState<string | null>(null);

  const [trustScore, setTrustScore] = useState(92);
  const [claims, setClaims] = useState<ClaimItem[]>([]);

  const defaultSamples = [
    {
      title: 'CRISPR Gene Editing Precision',
      text: 'CRISPR-Cas9 base editors introduce point mutations in cellular DNA without requiring double-stranded breaks. Recent structural biology papers in Nature confirm the deaminase domain preserves ~95% precision with minimal off-target Cas9 cleavage.',
    },
    {
      title: 'Quantum Advantage Demonstration',
      text: 'Superconducting quantum processors utilizing transmon qubits executed random circuit sampling faster than classical supercomputers in 2019, though subsequent tensor network simulations demonstrated classical algorithms can replicate the sampling benchmark with high fidelity.',
    },
    {
      title: 'Historical Discovery of Blood Circulation',
      text: 'William Harvey published Exercitatio Anatomica de Motu Cordis et Sanguinis in Animalibus in 1628, establishing the systemic circulation of blood pumped by the heart, refuting Galen’s earlier theory that venous and arterial blood were separate systems.',
    },
  ];

  const handleRunVerification = (textToVerify: string) => {
    if (!textToVerify.trim()) return;
    setIsVerifying(true);
    setHasResult(false);

    setTimeout(() => {
      const lower = textToVerify.toLowerCase();
      const isRefuted = lower.includes('flat earth') || lower.includes('fake') || lower.includes('moon landing hoax');
      const isMixed = lower.includes('quantum') || lower.includes('coffee') || lower.includes('diet');

      const mockClaims: ClaimItem[] = [
        {
          id: 'claim_1',
          text: textToVerify.slice(0, 120) + (textToVerify.length > 120 ? '...' : ''),
          verdict: isRefuted ? 'REFUTED' : isMixed ? 'PARTIALLY_SUPPORTED' : 'SUPPORTED',
          confidence: isRefuted ? 0.22 : isMixed ? 0.74 : 0.96,
          sources: [
            {
              title: 'Peer-Reviewed Scientific Index & Repository',
              url: 'https://scholar.archive.org/entry/1029',
              snippet: 'Corroborating measurements and historical documentation validate the empirical parameters asserted in the input excerpt.',
              relevance: 0.95,
            },
            {
              title: 'National Academy of Sciences Benchmark Dataset',
              url: 'https://pnas.org/doi/reference',
              snippet: 'Comprehensive multi-site replication confirms primary conclusions under standard experimental conditions.',
              relevance: 0.89,
            },
          ],
        },
        {
          id: 'claim_2',
          text: 'Supplementary factual premise cross-referenced against global verification registry.',
          verdict: isRefuted ? 'REFUTED' : 'SUPPORTED',
          confidence: isRefuted ? 0.15 : 0.91,
          sources: [
            {
              title: 'Global Fact Index & DOI Citation Archive',
              url: 'https://doi.org',
              snippet: 'Direct citation matches published standards and methodology specifications.',
              relevance: 0.92,
            },
          ],
        },
      ];

      setClaims(mockClaims);
      setExpandedClaimId(mockClaims[0].id);
      setTrustScore(isRefuted ? 19 : isMixed ? 68 : 94);
      setHasResult(true);
      setIsVerifying(false);
    }, 600);
  };

  const handleCopyReport = () => {
    const reportText = `Credence Verification Report\n============================\nInput: ${inputText}\nTrust Score: ${trustScore}%\nClaims: ${claims.length} analyzed\nGenerated by Credence AI Verification Engine`;
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify({ inputText, trustScore, claims }, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `verification_report_${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const filteredClaims = claims.filter((c) => {
    if (filterVerdict === 'ALL') return true;
    return c.verdict === filterVerdict;
  });

  return (
    <div className="flex-1 max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Header */}
      <div className="space-y-2">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-pastel-lavender-light dark:bg-purple-950/40 border border-pastel-lavender-border text-xs font-semibold text-purple-800 dark:text-purple-300">
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>Standalone Verification Studio</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-pastel-charcoal dark:text-pastel-charcoal-light">
          Inspect & Audit Factual Claims
        </h1>
        <p className="text-xs sm:text-sm text-pastel-slate dark:text-pastel-slate-light max-w-2xl leading-relaxed">
          Paste any AI-generated response, research excerpt, or draft to extract factual claims, calculate a trust score, and review primary citations.
        </p>
      </div>

      {/* Input Workbench Card */}
      <div className="bg-white dark:bg-pastel-surface-dark border border-pastel-border dark:border-pastel-border-dark rounded-3xl p-6 shadow-pastel space-y-4">
        <div className="flex items-center justify-between">
          <label className="text-xs font-bold uppercase tracking-wider text-pastel-charcoal dark:text-pastel-charcoal-light flex items-center space-x-2">
            <FileText className="w-4 h-4 text-pastel-lavender" />
            <span>Input Text or AI Response</span>
          </label>
          <span className="text-[11px] text-pastel-slate dark:text-pastel-slate-light font-mono">
            {inputText.length} characters
          </span>
        </div>

        <textarea
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          placeholder="Paste AI response, article excerpt, or statement here to verify..."
          rows={5}
          className="w-full bg-pastel-bg dark:bg-pastel-surface-elevated border border-pastel-border dark:border-pastel-border-dark rounded-2xl p-4 text-xs sm:text-sm text-pastel-charcoal dark:text-pastel-charcoal-light placeholder-pastel-slate focus:outline-none focus:border-pastel-lavender resize-y shadow-2xs"
        />

        {/* Pre-packaged Sample Buttons */}
        <div className="space-y-1.5">
          <span className="text-[11px] font-semibold text-pastel-slate uppercase tracking-wider block">
            Or load an academic sample:
          </span>
          <div className="flex flex-wrap gap-2">
            {defaultSamples.map((sample, idx) => (
              <button
                key={idx}
                onClick={() => {
                  setInputText(sample.text);
                  handleRunVerification(sample.text);
                }}
                className="text-xs px-3 py-1.5 rounded-xl bg-pastel-bg dark:bg-pastel-surface-elevated border border-pastel-border dark:border-pastel-border-dark text-pastel-slate dark:text-pastel-slate-light hover:border-pastel-lavender hover:text-purple-700 transition-all text-left"
              >
                "{sample.title}"
              </button>
            ))}
          </div>
        </div>

        {/* Action Button */}
        <div className="pt-2 flex justify-end">
          <button
            onClick={() => handleRunVerification(inputText)}
            disabled={!inputText.trim() || isVerifying}
            className="inline-flex items-center space-x-2 px-6 py-3 rounded-2xl text-xs sm:text-sm font-semibold bg-pastel-lavender hover:bg-pastel-lavender-hover text-white shadow-pastel hover:shadow-pastel-hover transition-all disabled:opacity-40"
          >
            <Search className={`w-4 h-4 ${isVerifying ? 'animate-spin' : ''}`} />
            <span>{isVerifying ? 'Cross-Referencing Evidence...' : 'Run Verification Audit'}</span>
          </button>
        </div>
      </div>

      {/* Results Section */}
      {hasResult && (
        <div className="space-y-6 animate-fade-in-up">
          {/* Trust Score & Overview Banner */}
          <div className="bg-white dark:bg-pastel-surface-dark border border-pastel-border dark:border-pastel-border-dark rounded-3xl p-6 sm:p-8 shadow-pastel space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-pastel-border/60">
              <div className="flex items-center space-x-3">
                <div className="w-12 h-12 rounded-2xl bg-pastel-mint-light text-emerald-800 border border-pastel-mint-border flex items-center justify-center font-bold text-lg">
                  {trustScore}%
                </div>
                <div>
                  <h3 className="text-lg font-bold text-pastel-charcoal dark:text-white">
                    Overall Trust Score: {trustScore >= 80 ? 'Highly Corroborated' : trustScore >= 50 ? 'Moderate Support' : 'Low Confidence'}
                  </h3>
                  <p className="text-xs text-pastel-slate dark:text-pastel-slate-light">
                    {claims.length} claims extracted and evaluated against authoritative scientific citations.
                  </p>
                </div>
              </div>

              {/* Export Tools */}
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleCopyReport}
                  className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-xl border border-pastel-border bg-white dark:bg-pastel-surface-elevated text-xs font-semibold text-pastel-charcoal dark:text-white hover:border-pastel-lavender transition-all"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy Summary'}</span>
                </button>
                <button
                  onClick={handleDownloadJSON}
                  className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-xl border border-pastel-border bg-white dark:bg-pastel-surface-elevated text-xs font-semibold text-pastel-charcoal dark:text-white hover:border-pastel-lavender transition-all"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download JSON</span>
                </button>
              </div>
            </div>

            {/* Filter Bar */}
            <div className="flex items-center justify-between pt-2">
              <div className="flex items-center space-x-2">
                <Filter className="w-3.5 h-3.5 text-pastel-slate" />
                <span className="text-xs font-semibold text-pastel-slate uppercase tracking-wider">
                  Filter Claims:
                </span>
              </div>
              <div className="flex items-center space-x-1.5 text-xs">
                {['ALL', 'SUPPORTED', 'PARTIALLY_SUPPORTED', 'REFUTED'].map((filter) => (
                  <button
                    key={filter}
                    onClick={() => setFilterVerdict(filter)}
                    className={`px-3 py-1 rounded-xl transition-all font-medium ${
                      filterVerdict === filter
                        ? 'bg-pastel-lavender text-white shadow-2xs'
                        : 'bg-pastel-bg dark:bg-pastel-surface-elevated text-pastel-slate hover:text-pastel-charcoal'
                    }`}
                  >
                    {filter === 'ALL' ? 'All' : filter.replace('_', ' ')}
                  </button>
                ))}
              </div>
            </div>

            {/* Claim Accordion Cards */}
            <div className="space-y-3 pt-2">
              {filteredClaims.map((claim, idx) => {
                const isExpanded = expandedClaimId === claim.id;

                return (
                  <div
                    key={claim.id}
                    className={`bg-white dark:bg-pastel-surface-elevated border rounded-2xl overflow-hidden transition-all shadow-2xs ${
                      isExpanded
                        ? 'border-pastel-lavender shadow-pastel-card'
                        : 'border-pastel-border dark:border-pastel-border-dark hover:border-pastel-lavender/60'
                    }`}
                  >
                    <div
                      onClick={() => setExpandedClaimId(isExpanded ? null : claim.id)}
                      className="p-4 bg-white dark:bg-pastel-surface-elevated hover:bg-pastel-lavender-light/30 cursor-pointer flex items-start justify-between gap-4"
                    >
                      <div className="flex items-start space-x-3">
                        <span className="text-xs font-bold text-pastel-lavender font-mono">
                          0{idx + 1}.
                        </span>
                        <div>
                          <p className="text-xs sm:text-sm font-semibold text-pastel-charcoal dark:text-pastel-charcoal-light leading-snug">
                            {claim.text}
                          </p>
                          <div className="flex items-center space-x-2 mt-1 text-[11px] text-pastel-slate dark:text-pastel-slate-light">
                            <span>Confidence: {Math.round(claim.confidence * 100)}%</span>
                            <span>•</span>
                            <span>{claim.sources.length} indexed citations</span>
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center space-x-2 flex-shrink-0">
                        {claim.verdict === 'SUPPORTED' && (
                          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold bg-pastel-mint-light text-emerald-900 border border-pastel-mint-border">
                            <CheckCircle className="w-3.5 h-3.5 mr-1 text-emerald-600" />
                            Verified
                          </span>
                        )}
                        {claim.verdict === 'PARTIALLY_SUPPORTED' && (
                          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold bg-pastel-peach-light text-amber-900 border border-pastel-peach-border">
                            <AlertTriangle className="w-3.5 h-3.5 mr-1 text-amber-600" />
                            Partially Supported
                          </span>
                        )}
                        {claim.verdict === 'REFUTED' && (
                          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold bg-pastel-rose-light text-rose-900 border border-pastel-rose-border">
                            <XCircle className="w-3.5 h-3.5 mr-1 text-rose-600" />
                            Refuted
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Citations Drilldown */}
                    {isExpanded && (
                      <div className="p-4 border-t border-pastel-border/70 bg-pastel-bg/60 dark:bg-pastel-surface-dark space-y-3">
                        <span className="text-[11px] font-semibold text-pastel-slate uppercase tracking-wider block">
                          Supporting Citations & Evidence:
                        </span>
                        {claim.sources.map((src, sIdx) => (
                          <div
                            key={sIdx}
                            className="p-3.5 bg-white dark:bg-pastel-surface-elevated rounded-xl border border-pastel-border dark:border-pastel-border-dark space-y-2 shadow-2xs"
                          >
                            <div className="flex items-center justify-between text-xs">
                              <a
                                href={src.url}
                                target="_blank"
                                rel="noreferrer"
                                className="font-semibold text-purple-700 dark:text-purple-300 hover:underline flex items-center space-x-1"
                              >
                                <span>{src.title}</span>
                                <ExternalLink className="w-3.5 h-3.5" />
                              </a>
                              <span className="text-[10px] font-medium bg-pastel-mint-light text-emerald-900 px-2 py-0.5 rounded border border-pastel-mint-border">
                                {Math.round(src.relevance * 100)}% Match
                              </span>
                            </div>
                            <p className="text-xs text-pastel-slate dark:text-pastel-slate-light leading-relaxed italic">
                              "{src.snippet}"
                            </p>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
