"""Reports API endpoints for Daranya."""

import json
import logging
import uuid
import csv
import io
from typing import Any, Dict, List, Optional
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, status, Response, BackgroundTasks
from pydantic import BaseModel

from app.api.dependencies import get_current_user
from app.core.database import database_manager
from app.repositories.verification_repository import (
    VerificationRepository,
    verification_repository,
)
from app.schemas.auth import UserResponse
from app.schemas.common import StandardResponse

logger = logging.getLogger("verifai.api.reports")

router = APIRouter()

class GenerateReportRequest(BaseModel):
    verification_id: uuid.UUID
    format: str  # 'pdf', 'json', 'csv'

@router.post(
    "",
    response_model=StandardResponse[Dict[str, Any]],
    summary="Generate a verification report",
)
async def generate_report(
    payload: GenerateReportRequest,
    current_user: UserResponse = Depends(get_current_user),
    repo: VerificationRepository = Depends(lambda: verification_repository),
) -> StandardResponse[Dict[str, Any]]:
    """Initiate report generation for a specific verification."""
    try:
        # Check ownership
        record = await repo.get_verification_by_id(payload.verification_id)
        if not record or str(record["user_id"]) != str(current_user.id):
            raise HTTPException(status_code=404, detail="Verification not found or unauthorized")
            
        if payload.format not in ['pdf', 'json', 'csv']:
            raise HTTPException(status_code=400, detail="Unsupported format. Use pdf, json, or csv")
            
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            report_id = await conn.fetchval(
                """INSERT INTO reports (verification_id, user_id, format, status, metadata) 
                   VALUES ($1, $2, $3, $4, $5::jsonb) RETURNING id""",
                payload.verification_id, current_user.id, payload.format, 'generated', json.dumps({})
            )
            
        return StandardResponse(success=True, data={"report_id": str(report_id), "status": "generated"})
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error generating report for user %s: %s", current_user.id, exc)
        raise HTTPException(status_code=500, detail="Failed to generate report")

@router.get(
    "",
    response_model=StandardResponse[List[Dict[str, Any]]],
    summary="List generated reports",
)
async def list_reports(
    current_user: UserResponse = Depends(get_current_user),
) -> StandardResponse[List[Dict[str, Any]]]:
    """List all reports generated by the user."""
    try:
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            records = await conn.fetch(
                "SELECT * FROM reports WHERE user_id = $1 ORDER BY created_at DESC",
                current_user.id
            )
            
        results = [dict(r) for r in records]
        # Convert UUIDs and Datetimes to string for JSON serialization
        for r in results:
            r["id"] = str(r["id"])
            r["verification_id"] = str(r["verification_id"])
            r["user_id"] = str(r["user_id"])
            r["metadata"] = json.loads(r["metadata"]) if isinstance(r["metadata"], str) else r["metadata"]
            
        return StandardResponse(success=True, data=results)
    except Exception as exc:
        logger.error("Error listing reports for user %s: %s", current_user.id, exc)
        raise HTTPException(status_code=500, detail="Failed to list reports")

@router.get(
    "/{report_id}",
    response_model=StandardResponse[Dict[str, Any]],
    summary="Get report metadata",
)
async def get_report_metadata(
    report_id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_user),
) -> StandardResponse[Dict[str, Any]]:
    """Retrieve metadata for a specific report."""
    try:
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            record = await conn.fetchrow(
                "SELECT * FROM reports WHERE id = $1 AND user_id = $2",
                report_id, current_user.id
            )
            
        if not record:
            raise HTTPException(status_code=404, detail="Report not found or unauthorized")
            
        result = dict(record)
        result["id"] = str(result["id"])
        result["verification_id"] = str(result["verification_id"])
        result["user_id"] = str(result["user_id"])
        
        return StandardResponse(success=True, data=result)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error fetching report %s: %s", report_id, exc)
        raise HTTPException(status_code=500, detail="Failed to fetch report")

@router.delete(
    "/{report_id}",
    response_model=StandardResponse[Dict[str, Any]],
    summary="Delete a report",
)
async def delete_report(
    report_id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_user),
) -> StandardResponse[Dict[str, Any]]:
    """Delete a generated report."""
    try:
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            result = await conn.execute(
                "DELETE FROM reports WHERE id = $1 AND user_id = $2",
                report_id, current_user.id
            )
            
        if result == "DELETE 0":
            raise HTTPException(status_code=404, detail="Report not found or unauthorized")
            
        return StandardResponse(success=True, data={"deleted": True})
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error deleting report %s: %s", report_id, exc)
        raise HTTPException(status_code=500, detail="Failed to delete report")

# --- Download Endpoint (Generates file content dynamically) ---

def generate_csv_content(verification_record: dict) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["verification_id", "timestamp", "claim_id", "claim", "verdict", "confidence", "decision_basis"])
    
    evidence = verification_record.get("evidence") or {}
    claim_results = evidence.get("claim_results", [])
    
    for c in claim_results:
        writer.writerow([
            str(verification_record["id"]),
            verification_record["created_at"].isoformat(),
            c.get("claim_id"),
            c.get("claim_text"),
            c.get("verdict"),
            c.get("confidence"),
            c.get("reason")
        ])
        
    return output.getvalue()

@router.get(
    "/{report_id}/download",
    summary="Download the generated report file",
)
async def download_report(
    report_id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_user),
    repo: VerificationRepository = Depends(lambda: verification_repository),
) -> Response:
    """Download the actual report file (PDF, JSON, CSV)."""
    try:
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            report_record = await conn.fetchrow(
                "SELECT * FROM reports WHERE id = $1 AND user_id = $2",
                report_id, current_user.id
            )
            
        if not report_record:
            raise HTTPException(status_code=404, detail="Report not found")
            
        verification_id = report_record["verification_id"]
        v_record = await repo.get_verification_by_id(verification_id)
        
        if not v_record:
            raise HTTPException(status_code=404, detail="Verification data not found")
            
        fmt = report_record["format"].lower()
        
        if fmt == "json":
            content = json.dumps(v_record, default=str)
            return Response(content=content, media_type="application/json", headers={"Content-Disposition": f"attachment; filename=report_{report_id}.json"})
            
        elif fmt == "csv":
            content = generate_csv_content(v_record)
            return Response(content=content, media_type="text/csv", headers={"Content-Disposition": f"attachment; filename=report_{report_id}.csv"})
            
        elif fmt == "pdf":
            # Very basic text implementation of PDF since we want to be free-tier friendly without heavy dependencies.
            # In a real app we'd use FPDF or similar.
            content = f"VERIFAI VERIFICATION REPORT\n\nVerification ID: {v_record['id']}\nVerdict: {v_record.get('verdict')}\nTrust Score: {v_record.get('trust_score')}\n\nClaims:\n"
            evidence = v_record.get("evidence") or {}
            for c in evidence.get("claim_results", []):
                content += f"- {c.get('claim_text')} ({c.get('verdict')})\n"
                
            return Response(content=content, media_type="text/plain", headers={"Content-Disposition": f"attachment; filename=report_{report_id}.txt"}) # Fallback to txt representation for now
            
        raise HTTPException(status_code=400, detail="Unsupported format")
        
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error downloading report %s: %s", report_id, exc)
        raise HTTPException(status_code=500, detail="Failed to download report")

# --- Compliance Report ---

@router.post(
    "/compliance",
    response_model=StandardResponse[Dict[str, Any]],
    summary="Generate compliance report",
)
async def generate_compliance_report(
    payload: GenerateReportRequest,
    current_user: UserResponse = Depends(get_current_user),
) -> StandardResponse[Dict[str, Any]]:
    """Initiate a compliance report generation."""
    try:
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            # Check ownership implicitly by trying to insert if verification is owned
            v_check = await conn.fetchval("SELECT id FROM verifications WHERE id = $1 AND user_id = $2", payload.verification_id, current_user.id)
            if not v_check:
                raise HTTPException(status_code=404, detail="Verification not found or unauthorized")
                
            report_id = await conn.fetchval(
                """INSERT INTO reports (verification_id, user_id, format, report_type, status, metadata) 
                   VALUES ($1, $2, $3, $4, $5, $6::jsonb) RETURNING id""",
                payload.verification_id, current_user.id, payload.format, 'compliance', 'generated', json.dumps({})
            )
            
        return StandardResponse(success=True, data={"report_id": str(report_id), "status": "generated"})
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error generating compliance report: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to generate compliance report")

@router.get(
    "/compliance/{report_id}",
    response_model=StandardResponse[Dict[str, Any]],
    summary="Get compliance report data",
)
async def get_compliance_report(
    report_id: uuid.UUID,
    current_user: UserResponse = Depends(get_current_user),
    repo: VerificationRepository = Depends(lambda: verification_repository),
) -> StandardResponse[Dict[str, Any]]:
    """Retrieve full compliance report JSON data."""
    try:
        pool = database_manager.get_pool()
        async with pool.acquire() as conn:
            report_record = await conn.fetchrow(
                "SELECT * FROM reports WHERE id = $1 AND user_id = $2 AND report_type = 'compliance'",
                report_id, current_user.id
            )
            
        if not report_record:
            raise HTTPException(status_code=404, detail="Compliance report not found or unauthorized")
            
        v_record = await repo.get_verification_by_id(report_record["verification_id"])
        
        # Build compliance object
        compliance_data = {
            "Verification": {
                "ID": str(v_record["id"]),
                "timestamp": v_record["created_at"].isoformat()
            },
            "AI_Response": {
                "original_response": v_record.get("claim", "")
            },
            "Claims": v_record.get("evidence", {}).get("claim_results", []),
            "Audit": [] # Would fetch from audit_events
        }
        
        async with pool.acquire() as conn:
            audit_records = await conn.fetch("SELECT stage, status, created_at FROM audit_events WHERE verification_id = $1 ORDER BY created_at ASC", v_record["id"])
            compliance_data["Audit"] = [{"stage": r["stage"], "status": r["status"], "timestamp": r["created_at"].isoformat()} for r in audit_records]
            
        return StandardResponse(success=True, data=compliance_data)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Error retrieving compliance report: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to retrieve compliance report")
